# Site settings
title: "Modern Dev Blog"
description: "A modern, fast, accessible blog powered by Jekyll and GitHub Pages"
url: "https://jukomol.github.io"
baseurl: "/blogs"
author:
  name: "jukomol"
  email: "jukomol@users.noreply.github.com"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - CONTRIBUTING.md
  - SITE_GUIDE.md

# GitHub Pages / Jekyll configuration
github_username: jukomol
repository: jukomol/blogs

# Giscus configuration
giscus:
      data-repo="jukomol/blogs"
      data-repo-id="R_kgDOPtfN_w"
      data-category="General"
      data-category-id="DIC_kwDOPtfN_84CvQ02"
      data-mapping="pathname"
      data-strict="0"
      data-reactions-enabled="1"
      data-emit-metadata="0"
      data-input-position="bottom"
      data-theme="preferred_color_scheme"
      data-lang="en"
      crossorigin="anonymous"

# Site features
features:
  dark_mode: true
  search: true
  comments: true
  
# SEO and social
twitter:
  username: jukomol
  card: summary_large_image

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "jukomol"
      show_excerpts: true
  - scope:
      path: ""
    values:
      layout: "default"
